
" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Show line numbers
" Turn of folding
" Show the cursor position all the time
set number
set nofoldenable
set ruler

" Enable incremental searching
" Set search to be case insensitive
" Set search to recognizes uppercase if it's specified
set incsearch
set ignorecase
set smartcase

" Setup tab styles
set softtabstop=2
set shiftwidth=2
set tabstop=2

" Switch syntax highlighting on and enable 256 colors
" Also switch on highlighting the last used search pattern.
set t_Co=256
syntax on
colorscheme ir_black256 
set hlsearch


" Enable file type detection.
" Also load indent files, to automatically do language-dependent indenting.
filetype plugin indent on

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" Also don't do it when the mark is in the first line, that is the default
" position when opening a file.
autocmd BufReadPost *
	\ if line("'\"") > 1 && line("'\"") <= line("$") |
	\   exe "normal! g`\"" |
	\ endif

" Setup Omni Completion
autocmd FileType html :set omnifunc=htmlcomplete#CompleteTags
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete


" Set text wrapping toggles
nmap <silent> ,w :set invwrap<CR>:set wrap?<CR>

" Edit the vimrc file
nmap <silent> ,ev :e $MYVIMRC<CR>
nmap <silent> ,sv :so $MYVIMRC<CR>


" NERD Tree configurations
nmap <F7> :NERDTreeToggle<CR>


